version: '3.7'

services:

  prometheus:
    image: courselabs/prometheus:v2.28.1
    ports: 
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics

networks:
  metrics:
    name: metrics
