services:

  mattermost:
    image: mattermost/mattermost-preview:6.5.0
    ports: 
      - 8065:8065
    extra_hosts:
    - "dockerhost:127.0.0.1"
    networks:
      - metrics

networks:
  metrics:
    name: metrics
