global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'demo'
    static_configs:
      - targets:
        - 'demo-service-1:8080'
        - 'demo-service-2:8081'
        - 'demo-service-3:8082'
